language: python
python:
  - "3.10"
service:
  - docker
install:
  - pip install -r requirements.txt
script:
  - python -m pytest tests/

before_deploy:
  - test -n "$HEROKU_API_KEY" || { echo "HEROKU_API_KEY is not set"; exit 1; }
  - heroku stack:set container --app cicd-docker-webapp
  - docker build -t cicd-docker-webapp .
  - docker tag cicd-docker-webapp:latest registry.heroku.com/cicd-docker-webapp
  - echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com

deploy:
  provider: script
  script: docker push registry.heroku.com/cicd-docker-webapp && heroku container:release web --app cicd_docker_webapp
  on:
    branch: main
